default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  database: manage_project_development
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost

test:
  database: manage_project_test
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
